### ISSUE TITLE
Actuators are expected to subscribe using the largest array type

### ISSUE THREAD

**Issue by silverv** [Zubax/sapog#15]
Actuators are expected to subscribe using the largest array type. Publishers would choose the array type # depending on the number of actuators in the group. The actuators would be expecting the largest array type,

**Comment by silverv** [comment]
I thought there was a vector of more than 8 somewhere, currently still using 8

**Comment by pavel-kirienko** [comment]
@silverv the largest is Vector31: https://github.com/UAVCAN/public_regulated_data_types/blob/master/reg/udral/service/actuator/common/sp/Vector31.0.1.uavcan
