### ISSUE TITLE
temperature_sensor::is_ok() is not true anymore after 10 minutes of waiting with the node idle

### ISSUE THREAD

**Issue by silverv** [Zubax/sapog#37]
Measured ordinary reached temperature on the Orel board is 79 degrees without the motor running just sending health messages.

**Comment by silverv** [comment]
Messages do not stop

**Comment by silverv** [comment]
This is also a manually repaired board

**Comment by pavel-kirienko** [comment]
Orel boards always run hot due to the construction of their power stage (excess energy is discarded from the LDO as heat). The is_ok flag is probably reset due to an I2C bus error -- this should be inspected with a logic analyzer.

**Comment by suzonch** [comment]
That's a bit too hot, maybe measure the voltages and resistance or LDO?

**Comment by silverv** [comment]
Fixed
